# @generated by datamodel-codegen from spec/openapi.yaml. DO NOT EDIT. Regenerate: task sdk:py:gen

from __future__ import annotations

from typing import Any, Literal, TypedDict

from typing_extensions import NotRequired


class Health(TypedDict):
    status: str
    version: str
    db: str
    queue: str
    workmem: Literal['ok', 'degraded', 'disabled']
    embedder: str
    extraction: str


class CreateEventRequest(TypedDict):
    run_id: str
    agent_id: str
    payload: dict[str, Any]


class CreateEventResponse(TypedDict):
    event_id: str
    seq: int


class CreateRunResponse(TypedDict):
    run_id: str
    created_at: str


class PackRequest(TypedDict):
    run_id: str
    query: str
    min_seq: NotRequired[int]
    scopes: NotRequired[list[str]]
    limit: NotRequired[int]
    token_budget: NotRequired[int]


class PackSource(TypedDict):
    id: str
    kind: str
    score: float
    section: str


class Memory(TypedDict):
    id: str
    kind: str
    content: str
    created_by_agent: str
    created_at: str
    version: int
    trust_tier: str
    review_status: str
    scope_keys: list[str]
    source_event_id: NotRequired[str]
    run_id: NotRequired[str]


class MemoryListResponse(TypedDict):
    memories: list[Memory]
    has_more: bool
    next_cursor: NotRequired[str]


class MemoryVersion(TypedDict):
    version: int
    content: str
    changed_by: NotRequired[str]
    reason: NotRequired[str]
    created_at: str


class MemoryVersionListResponse(TypedDict):
    versions: list[MemoryVersion]


class RunTraceEntry(TypedDict):
    id: str
    created_at: str
    query: str
    covered_seq: NotRequired[int]
    freshness_lag_ms: NotRequired[int]
    latency_ms: NotRequired[int]
    memory_ids: list[str]
    pack_hash: NotRequired[str]


class RunTraceResponse(TypedDict):
    packs: list[RunTraceEntry]
    has_more: bool
    next_cursor: NotRequired[str]


class Error(TypedDict):
    """
    The shape of every error this API returns, including the ones the router produces before a handler runs: a path that matches no endpoint answers 404 with code `unknown_route`, and an endpoint addressed with a method it does not serve answers 405 with code `method_not_allowed`. A client can therefore decode this body for any non-2xx response without special-casing those two.
    """

    message: str
    code: NotRequired[str]


class PackResponse(TypedDict):
    text: str
    sources: list[PackSource]
    covered_seq: int
    freshness_lag_ms: int
    saved_tokens: int
    working_source: Literal['live', 'durable', 'unavailable']
    truncated: bool
    degraded: NotRequired[list[Literal['dense']]]
