# @generated by datamodel-codegen from spec/openapi.yaml. DO NOT EDIT. Regenerate: task sdk:py:gen

from __future__ import annotations

from typing import Any, Literal, TypedDict

from typing_extensions import NotRequired


class Health(TypedDict):
    status: str
    version: str
    db: str
    queue: str
    workmem: Literal['ok', 'degraded', 'disabled']


class CreateEventRequest(TypedDict):
    run_id: str
    agent_id: str
    payload: dict[str, Any]


class CreateEventResponse(TypedDict):
    event_id: str
    seq: int


class CreateRunResponse(TypedDict):
    run_id: str
    created_at: str


class PackRequest(TypedDict):
    run_id: str
    query: str
    min_seq: NotRequired[int]
    scopes: NotRequired[list[str]]
    limit: NotRequired[int]
    token_budget: NotRequired[int]


class PackSource(TypedDict):
    id: str
    kind: str
    score: float
    section: str


class Error(TypedDict):
    message: str
    code: NotRequired[str]


class PackResponse(TypedDict):
    text: str
    sources: list[PackSource]
    covered_seq: int
    freshness_lag_ms: int
    saved_tokens: int
    working_source: Literal['live', 'durable', 'skipped']
    truncated: bool
