// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveClaimsByEntities = `-- name: GetActiveClaimsByEntities :many
SELECT c.entity_id, c.predicate, c.id, c.value, e.run_id, e.seq
FROM claims c
LEFT JOIN events e ON e.id = c.source_event_id AND e.project_id = c.project_id
WHERE c.project_id = $1
  AND c.entity_id = ANY($2::uuid[])
  AND c.superseded_by IS NULL
`

type GetActiveClaimsByEntitiesParams struct {
	ProjectID pgtype.UUID   `json:"project_id"`
	EntityIds []pgtype.UUID `json:"entity_ids"`
}

type GetActiveClaimsByEntitiesRow struct {
	EntityID  pgtype.UUID `json:"entity_id"`
	Predicate string      `json:"predicate"`
	ID        pgtype.UUID `json:"id"`
	Value     []byte      `json:"value"`
	RunID     pgtype.UUID `json:"run_id"`
	Seq       *int64      `json:"seq"`
}

// The currently-active claims for a set of entities in one project — one row per (entity, predicate) that
// has one, each carrying its value and the provenance (run + per-run seq) of the event it was distilled
// from. The write path fetches them in a single round-trip (rather than once per claim) and resolves
// conflicts against an in-memory overlay it updates as it supersedes and inserts within the pass, so two
// claims for the same subject in one pass still resolve last-write-wins — exactly as a per-claim re-read
// would, since a transaction sees its own writes. A policy needs the stored value (e.g. FieldMerge combines
// it with the incoming one) and the provenance feeds the recorded reason. Fetching by entity (not the exact
// (entity, predicate) subject) keeps this to one array parameter; a pass touches few entities, and the
// caller keys its overlay by the full subject, so the extra rows for other predicates of the same entity
// are simply never looked up. The partial-unique index leads with (project_id, entity_id), so this probes
// it. run_id/seq are NULL for a manual claim with no source event; the events join is project-scoped so it
// stays within the tenant.
func (q *Queries) GetActiveClaimsByEntities(ctx context.Context, arg GetActiveClaimsByEntitiesParams) ([]GetActiveClaimsByEntitiesRow, error) {
	rows, err := q.db.Query(ctx, getActiveClaimsByEntities, arg.ProjectID, arg.EntityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveClaimsByEntitiesRow
	for rows.Next() {
		var i GetActiveClaimsByEntitiesRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Predicate,
			&i.ID,
			&i.Value,
			&i.RunID,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClaim = `-- name: InsertClaim :exec
INSERT INTO claims (id, memory_id, project_id, entity_id, predicate, value, event_time, source_event_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertClaimParams struct {
	ID            pgtype.UUID        `json:"id"`
	MemoryID      pgtype.UUID        `json:"memory_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Predicate     string             `json:"predicate"`
	Value         []byte             `json:"value"`
	EventTime     pgtype.Timestamptz `json:"event_time"`
	SourceEventID pgtype.UUID        `json:"source_event_id"`
}

// Insert one claim with an explicit id. The write path pre-generates the id so it can point a
// superseded claim at this replacement before this row exists (see SupersedeActiveClaimBySubject);
// the self-FK is deferred, so the pointer is validated at commit. memory_id is nullable — a standalone
// claim (no co-produced memory) has none — while source_event_id carries provenance on every claim.
func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) error {
	_, err := q.db.Exec(ctx, insertClaim,
		arg.ID,
		arg.MemoryID,
		arg.ProjectID,
		arg.EntityID,
		arg.Predicate,
		arg.Value,
		arg.EventTime,
		arg.SourceEventID,
	)
	return err
}

const supersedeActiveClaimBySubject = `-- name: SupersedeActiveClaimBySubject :execrows
UPDATE claims
SET superseded_by = $1,
    resolution_reason = $2
WHERE project_id = $3
  AND entity_id = $4
  AND predicate = $5
  AND superseded_by IS NULL
`

type SupersedeActiveClaimBySubjectParams struct {
	SupersededBy     pgtype.UUID `json:"superseded_by"`
	ResolutionReason *string     `json:"resolution_reason"`
	ProjectID        pgtype.UUID `json:"project_id"`
	EntityID         pgtype.UUID `json:"entity_id"`
	Predicate        string      `json:"predicate"`
}

// Close the currently-active claim for a subject (project, entity, predicate) by pointing it at its
// replacement and stamping the resolution reason on it (the superseded row is the one whose state
// changed), so a new active claim for the same subject can be inserted without violating
// claims_active_subject_key. At most one row matches (the partial-unique index guarantees it), so the
// rowcount is 0 (first assertion) or 1 (a policy resolved a conflict). The replacement id need not
// exist yet — superseded_by is DEFERRABLE, validated at commit once the caller inserts it next.
func (q *Queries) SupersedeActiveClaimBySubject(ctx context.Context, arg SupersedeActiveClaimBySubjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeActiveClaimBySubject,
		arg.SupersededBy,
		arg.ResolutionReason,
		arg.ProjectID,
		arg.EntityID,
		arg.Predicate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeClaim = `-- name: SupersedeClaim :execrows
UPDATE claims
SET superseded_by = $2
WHERE id = $1 AND superseded_by IS NULL AND project_id = $3
`

type SupersedeClaimParams struct {
	ID           pgtype.UUID `json:"id"`
	SupersededBy pgtype.UUID `json:"superseded_by"`
	ProjectID    pgtype.UUID `json:"project_id"`
}

// Supersede a specific claim by id (only if still active), scoped to its project. Distinct from
// SupersedeActiveClaimBySubject, which closes whichever claim is active for a subject.
func (q *Queries) SupersedeClaim(ctx context.Context, arg SupersedeClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeClaim, arg.ID, arg.SupersededBy, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
