// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertClaim = `-- name: InsertClaim :one
INSERT INTO claims (memory_id, project_id, entity_id, predicate, value, event_time)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, memory_id, project_id, entity_id, predicate, value, event_time, superseded_by, created_at
`

type InsertClaimParams struct {
	MemoryID  pgtype.UUID        `json:"memory_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Predicate string             `json:"predicate"`
	Value     []byte             `json:"value"`
	EventTime pgtype.Timestamptz `json:"event_time"`
}

func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, insertClaim,
		arg.MemoryID,
		arg.ProjectID,
		arg.EntityID,
		arg.Predicate,
		arg.Value,
		arg.EventTime,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.ProjectID,
		&i.EntityID,
		&i.Predicate,
		&i.Value,
		&i.EventTime,
		&i.SupersededBy,
		&i.CreatedAt,
	)
	return i, err
}

const supersedeClaim = `-- name: SupersedeClaim :execrows
UPDATE claims
SET superseded_by = $2
WHERE id = $1 AND superseded_by IS NULL
`

type SupersedeClaimParams struct {
	ID           pgtype.UUID `json:"id"`
	SupersededBy pgtype.UUID `json:"superseded_by"`
}

// Supersede only a currently-active claim; the row count lets the caller detect a
// no-op (the claim was already superseded), keeping the one-active-per-subject
// invariant enforceable from the write path rather than from the index alone.
func (q *Queries) SupersedeClaim(ctx context.Context, arg SupersedeClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeClaim, arg.ID, arg.SupersededBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
