// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const getEmbedding = `-- name: GetEmbedding :one
SELECT project_id, memory_id, model_id, vec, created_at
FROM embeddings
WHERE memory_id = $1 AND model_id = $2
`

type GetEmbeddingParams struct {
	MemoryID pgtype.UUID `json:"memory_id"`
	ModelID  string      `json:"model_id"`
}

func (q *Queries) GetEmbedding(ctx context.Context, arg GetEmbeddingParams) (Embedding, error) {
	row := q.db.QueryRow(ctx, getEmbedding, arg.MemoryID, arg.ModelID)
	var i Embedding
	err := row.Scan(
		&i.ProjectID,
		&i.MemoryID,
		&i.ModelID,
		&i.Vec,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEmbedding = `-- name: UpsertEmbedding :one
INSERT INTO embeddings (project_id, memory_id, model_id, vec)
VALUES ($1, $2, $3, $4)
ON CONFLICT (memory_id, model_id) DO UPDATE SET vec = EXCLUDED.vec
RETURNING project_id, memory_id, model_id, vec, created_at
`

type UpsertEmbeddingParams struct {
	ProjectID pgtype.UUID     `json:"project_id"`
	MemoryID  pgtype.UUID     `json:"memory_id"`
	ModelID   string          `json:"model_id"`
	Vec       pgvector.Vector `json:"vec"`
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) (Embedding, error) {
	row := q.db.QueryRow(ctx, upsertEmbedding,
		arg.ProjectID,
		arg.MemoryID,
		arg.ModelID,
		arg.Vec,
	)
	var i Embedding
	err := row.Scan(
		&i.ProjectID,
		&i.MemoryID,
		&i.ModelID,
		&i.Vec,
		&i.CreatedAt,
	)
	return i, err
}
