// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO entities (project_id, name, type, aliases)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertEntityParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Aliases   []string    `json:"aliases"`
}

// Get-or-create the entity named (project_id, name), returning its id. On conflict the no-op SET
// (name = itself) is what lets RETURNING yield the existing row's id — ON CONFLICT DO NOTHING would
// return no row. type and aliases are kept as first written (a project-scoped type registry and
// alias-merge resolution land in a later phase); this is how the write path resolves a mention or a
// claim's subject to an entity id.
func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertEntity,
		arg.ProjectID,
		arg.Name,
		arg.Type,
		arg.Aliases,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
