// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceCoveredSeq = `-- name: AdvanceCoveredSeq :execrows
UPDATE runs
SET covered_seq = $1,
    extraction_batch_id = NULL,
    extraction_batch_covered_seq = NULL
WHERE id = $2
  AND project_id = $3
  AND covered_seq < $1
`

type AdvanceCoveredSeqParams struct {
	CoveredSeq int64       `json:"covered_seq"`
	RunID      pgtype.UUID `json:"run_id"`
	ProjectID  pgtype.UUID `json:"project_id"`
}

// Advance a run's extraction checkpoint to the highest seq the pass consumed, never backward, and
// clear any pending batch state in the same single-row UPDATE. A committed pass has no batch in
// flight; the batch columns are already NULL for a realtime pass, so clearing them is a no-op there
// and drops the recorded handle for a collected economy pass. The covered_seq < guard keeps the
// checkpoint monotonic and makes a duplicate advance a no-op (0 rows). This runs in the same
// transaction as the pass's memory writes, so the checkpoint, the rows it accounts for, and the batch
// clear commit together — the atomicity that makes a coalesced pass idempotent.
func (q *Queries) AdvanceCoveredSeq(ctx context.Context, arg AdvanceCoveredSeqParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceCoveredSeq, arg.CoveredSeq, arg.RunID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAllEvents = `-- name: CountAllEvents :one
SELECT count(*) FROM events
`

// lore:tenant-exempt: global by design; must run under a bypass role (readonly/ops), NOT lore_app — RLS would silently scope it
func (q *Queries) CountAllEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, run_id, agent_id, payload, created_at, seq, project_id
FROM events
WHERE project_id = $1 AND id = $2
`

type GetEventParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.ProjectID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AgentID,
		&i.Payload,
		&i.CreatedAt,
		&i.Seq,
		&i.ProjectID,
	)
	return i, err
}

const getRunExtractionState = `-- name: GetRunExtractionState :one
SELECT r.extraction_batch_id,
       r.extraction_batch_covered_seq,
       (SELECT extraction_mode FROM projects WHERE projects.id = r.project_id) AS extraction_mode
FROM runs r
WHERE r.id = $1 AND r.project_id = $2
`

type GetRunExtractionStateParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type GetRunExtractionStateRow struct {
	ExtractionBatchID         *string `json:"extraction_batch_id"`
	ExtractionBatchCoveredSeq *int64  `json:"extraction_batch_covered_seq"`
	ExtractionMode            string  `json:"extraction_mode"`
}

// The run's extraction mode (from its project) and any pending batch, in one project-scoped read. The
// mode comes via a scalar subquery so the statement stays single-table (runs) for the generated return
// type; a NULL extraction_batch_id means no batch is in flight and the pass is in its submit/realtime
// phase, while a non-NULL one means an earlier attempt submitted a batch that is awaiting collection.
func (q *Queries) GetRunExtractionState(ctx context.Context, arg GetRunExtractionStateParams) (GetRunExtractionStateRow, error) {
	row := q.db.QueryRow(ctx, getRunExtractionState, arg.RunID, arg.ProjectID)
	var i GetRunExtractionStateRow
	err := row.Scan(&i.ExtractionBatchID, &i.ExtractionBatchCoveredSeq, &i.ExtractionMode)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
WITH bumped AS (
    UPDATE runs AS r
    SET last_seq = r.last_seq + 1
    WHERE r.id = $3
    RETURNING r.id, r.project_id, r.last_seq
)
INSERT INTO events (project_id, run_id, agent_id, payload, seq)
SELECT bumped.project_id, bumped.id, $1, $2, bumped.last_seq
FROM bumped
RETURNING events.id, events.run_id, events.agent_id, events.payload, events.created_at, events.seq, events.project_id
`

type InsertEventParams struct {
	AgentID string      `json:"agent_id"`
	Payload []byte      `json:"payload"`
	RunID   pgtype.UUID `json:"run_id"`
}

// Assigns the event's per-run seq inside the write transaction. A data-modifying CTE bumps the
// run's counter — a single-row UPDATE ... RETURNING whose row lock serialises concurrent writers
// of the same run, so seq is gap-free and monotonic without an advisory lock — and the INSERT
// stamps the returned value onto the event. project_id is taken from the same run row, so it can
// never disagree with the run's project (the composite (project_id, run_id) foreign key backstops
// it). An unknown run_id updates no row, the CTE is empty, nothing is inserted, and no row is
// returned (pgx.ErrNoRows) — the caller's "unknown run" signal.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent, arg.AgentID, arg.Payload, arg.RunID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AgentID,
		&i.Payload,
		&i.CreatedAt,
		&i.Seq,
		&i.ProjectID,
	)
	return i, err
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT id, run_id, agent_id, payload, created_at, seq, project_id
FROM events
WHERE events.project_id = $1 AND events.run_id = $2
  AND events.seq > (SELECT covered_seq FROM runs WHERE runs.id = $2)
ORDER BY events.seq
`

type ListRunEventsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

// A run's not-yet-extracted events (seq past the run's checkpoint) in seq order, for the coalesced
// extraction pass. The covered_seq subquery scopes the read to events an earlier pass has not
// already consumed, so a re-enqueued or retried job never re-reads them. Project-scoped so it is
// tenant-safe and (under RLS) reads only the caller's project.
func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRunEvents, arg.ProjectID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AgentID,
			&i.Payload,
			&i.CreatedAt,
			&i.Seq,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runExtractionReadiness = `-- name: RunExtractionReadiness :one
SELECT count(*)::bigint AS event_count,
       coalesce(extract(epoch FROM now() - max(events.created_at)), 0)::double precision AS idle_seconds
FROM events
WHERE events.project_id = $1 AND events.run_id = $2
  AND events.seq > (SELECT covered_seq FROM runs WHERE runs.id = $2)
`

type RunExtractionReadinessParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

type RunExtractionReadinessRow struct {
	EventCount  int64   `json:"event_count"`
	IdleSeconds float64 `json:"idle_seconds"`
}

// Debounce inputs for one run's coalesced extraction, measured over its not-yet-extracted events
// (seq past the checkpoint): how many there are, and how long since the most recent one measured by
// the database clock (so there is no app/DB clock skew). With none pending, event_count is 0 and
// idle_seconds is 0, so the caller treats the drained run as ready (nothing to do). Project-scoped.
func (q *Queries) RunExtractionReadiness(ctx context.Context, arg RunExtractionReadinessParams) (RunExtractionReadinessRow, error) {
	row := q.db.QueryRow(ctx, runExtractionReadiness, arg.ProjectID, arg.RunID)
	var i RunExtractionReadinessRow
	err := row.Scan(&i.EventCount, &i.IdleSeconds)
	return i, err
}

const setRunBatch = `-- name: SetRunBatch :execrows
UPDATE runs
SET extraction_batch_id = $1,
    extraction_batch_covered_seq = $2
WHERE id = $3 AND project_id = $4
`

type SetRunBatchParams struct {
	BatchID         *string     `json:"batch_id"`
	BatchCoveredSeq *int64      `json:"batch_covered_seq"`
	RunID           pgtype.UUID `json:"run_id"`
	ProjectID       pgtype.UUID `json:"project_id"`
}

// Record the handle and covered seq of the batch a run's economy-mode pass just submitted, so a later
// attempt collects it. Project-scoped. AdvanceCoveredSeq clears these when the collected pass commits.
func (q *Queries) SetRunBatch(ctx context.Context, arg SetRunBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunBatch,
		arg.BatchID,
		arg.BatchCoveredSeq,
		arg.RunID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
