// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inspect.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMemory = `-- name: GetMemory :one

SELECT id, kind, content, created_by_agent, created_at, version, trust_tier, review_status, scope_keys, source_event_id
FROM memories
WHERE project_id = $1 AND id = $2
  AND valid_to IS NULL AND superseded_by IS NULL
`

type GetMemoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

type GetMemoryRow struct {
	ID             pgtype.UUID        `json:"id"`
	Kind           string             `json:"kind"`
	Content        string             `json:"content"`
	CreatedByAgent *string            `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Version        int32              `json:"version"`
	TrustTier      string             `json:"trust_tier"`
	ReviewStatus   string             `json:"review_status"`
	ScopeKeys      []string           `json:"scope_keys"`
	SourceEventID  pgtype.UUID        `json:"source_event_id"`
}

// Inspection read/soft-delete surface (GET /v1/memories[/{id}][/versions], DELETE /v1/memories/{id},
// GET /v1/runs/{id}/trace). Every query is project-scoped for tenant isolation (the RLS belt is the second
// line); the list/get/delete queries all filter to the currently-valid head (valid_to IS NULL AND
// superseded_by IS NULL) so a soft-deleted or superseded memory is invisible to reads exactly as it is to
// retrieval and packs.
// One currently-valid memory by id. A soft-deleted, superseded, unknown, or cross-project id returns no row
// (the handler maps that to the same 404, so a key cannot probe another project's memory ids).
func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (GetMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMemory, arg.ProjectID, arg.ID)
	var i GetMemoryRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Content,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.Version,
		&i.TrustTier,
		&i.ReviewStatus,
		&i.ScopeKeys,
		&i.SourceEventID,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (project_id, actor, action, target, detail)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Actor     string      `json:"actor"`
	Action    string      `json:"action"`
	Target    *string     `json:"target"`
	Detail    []byte      `json:"detail"`
}

// Append one audit_log row. The table is INSERT-only (a trigger rejects UPDATE/DELETE), so this records an
// immutable trail entry. project_id scopes it to the tenant; actor/action/target/detail record who did what to
// which object (e.g. actor=api, action=memory.delete, target=<memory id>).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ProjectID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Detail,
	)
	return err
}

const listMemoriesBrowse = `-- name: ListMemoriesBrowse :many
SELECT id, kind, content, created_by_agent, created_at, version, trust_tier, review_status, scope_keys, source_event_id
FROM memories m
WHERE m.project_id = $1
  AND m.superseded_by IS NULL AND m.valid_to IS NULL
  AND ($2::text IS NULL OR m.kind = $2)
  AND ($3::text IS NULL OR m.trust_tier = $3)
  AND ($4::text IS NULL OR m.review_status = $4)
  AND ($5::uuid IS NULL OR m.source_event_id IN (
        SELECT e.id FROM events e WHERE e.project_id = $1 AND e.run_id = $5))
  AND ($6::timestamptz IS NULL
       OR (m.created_at, m.id) < ($6::timestamptz, $7::uuid))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $8::int
`

type ListMemoriesBrowseParams struct {
	ProjectID       pgtype.UUID        `json:"project_id"`
	Kind            *string            `json:"kind"`
	TrustTier       *string            `json:"trust_tier"`
	ReviewStatus    *string            `json:"review_status"`
	RunID           pgtype.UUID        `json:"run_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

type ListMemoriesBrowseRow struct {
	ID             pgtype.UUID        `json:"id"`
	Kind           string             `json:"kind"`
	Content        string             `json:"content"`
	CreatedByAgent *string            `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Version        int32              `json:"version"`
	TrustTier      string             `json:"trust_tier"`
	ReviewStatus   string             `json:"review_status"`
	ScopeKeys      []string           `json:"scope_keys"`
	SourceEventID  pgtype.UUID        `json:"source_event_id"`
}

// Browse mode: the project's currently-valid memories, newest first, with optional column filters and a
// keyset cursor. The cursor is the (created_at, id) of the last row of the previous page; the row-value
// comparison walks the (created_at DESC, id DESC) order without an offset scan. run_id narrows to memories
// distilled from that run's events (a memory with no source event is excluded when the run filter is set).
// The handler fetches lim = limit + 1 to learn whether a further page exists.
func (q *Queries) ListMemoriesBrowse(ctx context.Context, arg ListMemoriesBrowseParams) ([]ListMemoriesBrowseRow, error) {
	rows, err := q.db.Query(ctx, listMemoriesBrowse,
		arg.ProjectID,
		arg.Kind,
		arg.TrustTier,
		arg.ReviewStatus,
		arg.RunID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoriesBrowseRow
	for rows.Next() {
		var i ListMemoriesBrowseRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Content,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.Version,
			&i.TrustTier,
			&i.ReviewStatus,
			&i.ScopeKeys,
			&i.SourceEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesSearch = `-- name: ListMemoriesSearch :many
SELECT id, kind, content, created_by_agent, created_at, version, trust_tier, review_status, scope_keys, source_event_id,
       ts_rank_cd(to_tsvector('english', m.content), websearch_to_tsquery('english', $1::text))::float8 AS rank
FROM memories m
WHERE m.project_id = $2
  AND m.superseded_by IS NULL AND m.valid_to IS NULL
  AND ($3::text IS NULL OR m.kind = $3)
  AND ($4::text IS NULL OR m.trust_tier = $4)
  AND ($5::text IS NULL OR m.review_status = $5)
  AND ($6::uuid IS NULL OR m.source_event_id IN (
        SELECT e.id FROM events e WHERE e.project_id = $2 AND e.run_id = $6))
  AND to_tsvector('english', m.content) @@ websearch_to_tsquery('english', $1::text)
ORDER BY rank DESC, m.id ASC
LIMIT $7::int
`

type ListMemoriesSearchParams struct {
	QueryText    string      `json:"query_text"`
	ProjectID    pgtype.UUID `json:"project_id"`
	Kind         *string     `json:"kind"`
	TrustTier    *string     `json:"trust_tier"`
	ReviewStatus *string     `json:"review_status"`
	RunID        pgtype.UUID `json:"run_id"`
	Lim          int32       `json:"lim"`
}

type ListMemoriesSearchRow struct {
	ID             pgtype.UUID        `json:"id"`
	Kind           string             `json:"kind"`
	Content        string             `json:"content"`
	CreatedByAgent *string            `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Version        int32              `json:"version"`
	TrustTier      string             `json:"trust_tier"`
	ReviewStatus   string             `json:"review_status"`
	ScopeKeys      []string           `json:"scope_keys"`
	SourceEventID  pgtype.UUID        `json:"source_event_id"`
	Rank           float64            `json:"rank"`
}

// Search mode: the same filtered set, but matched and ranked by a lexical full-text query over content. It
// reuses the identical to_tsvector('english', content) @@ websearch_to_tsquery('english', ...) predicate the
// dense read path's lexical leg uses, so it rides the same expression GIN index (a drift from that expression
// silently falls to a sequential scan). It needs NO embedding model — search works on a deployment that never
// pinned one. Ranked by lexical relevance with an id tie-break for a stable order; the handler fetches
// lim = limit + 1 for the has_more signal. Search returns the first page only (no keyset cursor in v0).
func (q *Queries) ListMemoriesSearch(ctx context.Context, arg ListMemoriesSearchParams) ([]ListMemoriesSearchRow, error) {
	rows, err := q.db.Query(ctx, listMemoriesSearch,
		arg.QueryText,
		arg.ProjectID,
		arg.Kind,
		arg.TrustTier,
		arg.ReviewStatus,
		arg.RunID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoriesSearchRow
	for rows.Next() {
		var i ListMemoriesSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Content,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.Version,
			&i.TrustTier,
			&i.ReviewStatus,
			&i.ScopeKeys,
			&i.SourceEventID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunPackLogs = `-- name: ListRunPackLogs :many
SELECT id, query, covered_seq, freshness_lag_ms, latency_ms, memory_ids, pack_hash, created_at
FROM pack_logs
WHERE project_id = $1 AND run_id = $2
  AND ($3::timestamptz IS NULL
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListRunPackLogsParams struct {
	ProjectID       pgtype.UUID        `json:"project_id"`
	RunID           pgtype.UUID        `json:"run_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

type ListRunPackLogsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Query          string             `json:"query"`
	CoveredSeq     *int64             `json:"covered_seq"`
	FreshnessLagMs *int32             `json:"freshness_lag_ms"`
	LatencyMs      *int32             `json:"latency_ms"`
	MemoryIds      []pgtype.UUID      `json:"memory_ids"`
	PackHash       []byte             `json:"pack_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// A run's context-pack history, newest first, keyset-paginated on (created_at, id). Rides the
// pack_logs (project_id, created_at) index. pack_hash and the coverage/timing columns are nullable and passed
// through as-is. The handler fetches lim = limit + 1 for the has_more signal.
func (q *Queries) ListRunPackLogs(ctx context.Context, arg ListRunPackLogsParams) ([]ListRunPackLogsRow, error) {
	rows, err := q.db.Query(ctx, listRunPackLogs,
		arg.ProjectID,
		arg.RunID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunPackLogsRow
	for rows.Next() {
		var i ListRunPackLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Query,
			&i.CoveredSeq,
			&i.FreshnessLagMs,
			&i.LatencyMs,
			&i.MemoryIds,
			&i.PackHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memoryRowExists = `-- name: MemoryRowExists :one
SELECT EXISTS(SELECT 1 FROM memories WHERE project_id = $1 AND id = $2)
`

type MemoryRowExistsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// Whether a memory row exists in the project at all — INCLUDING soft-deleted and superseded rows — so the
// version-history endpoint can 404 an unknown id while still serving a deleted memory's history.
func (q *Queries) MemoryRowExists(ctx context.Context, arg MemoryRowExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, memoryRowExists, arg.ProjectID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const runRowExists = `-- name: RunRowExists :one
SELECT EXISTS(SELECT 1 FROM runs WHERE project_id = $1 AND id = $2)
`

type RunRowExistsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// Whether a run exists in the project, so the run-trace endpoint can 404 an unknown run (a real run with no
// packs yet is a 200 empty page, not a 404).
func (q *Queries) RunRowExists(ctx context.Context, arg RunRowExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, runRowExists, arg.ProjectID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteMemory = `-- name: SoftDeleteMemory :one
UPDATE memories SET valid_to = now()
WHERE project_id = $1 AND id = $2
  AND valid_to IS NULL AND superseded_by IS NULL
RETURNING id
`

type SoftDeleteMemoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

// Soft-delete the currently-valid memory: stamp its validity window closed so it drops out of every read
// (retrieval, packs, list) that filters valid_to IS NULL, while the row and its version history are retained.
// Idempotent per live row: a second delete (or an unknown/superseded/cross-project id) updates no row, which
// the handler maps to a 404.
func (q *Queries) SoftDeleteMemory(ctx context.Context, arg SoftDeleteMemoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteMemory, arg.ProjectID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
