// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory_scopes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMemoryScope = `-- name: InsertMemoryScope :one
INSERT INTO memory_scopes (memory_id, scope_type, scope_id)
VALUES ($1, $2, $3)
RETURNING memory_id, scope_type, scope_id, created_at
`

type InsertMemoryScopeParams struct {
	MemoryID  pgtype.UUID `json:"memory_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   string      `json:"scope_id"`
}

func (q *Queries) InsertMemoryScope(ctx context.Context, arg InsertMemoryScopeParams) (MemoryScope, error) {
	row := q.db.QueryRow(ctx, insertMemoryScope, arg.MemoryID, arg.ScopeType, arg.ScopeID)
	var i MemoryScope
	err := row.Scan(
		&i.MemoryID,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
	)
	return i, err
}

const listMemoryScopes = `-- name: ListMemoryScopes :many
SELECT memory_id, scope_type, scope_id, created_at
FROM memory_scopes
WHERE memory_id = $1
ORDER BY scope_type, scope_id
`

func (q *Queries) ListMemoryScopes(ctx context.Context, memoryID pgtype.UUID) ([]MemoryScope, error) {
	rows, err := q.db.Query(ctx, listMemoryScopes, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryScope
	for rows.Next() {
		var i MemoryScope
		if err := rows.Scan(
			&i.MemoryID,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
