// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMemory = `-- name: InsertMemory :one
INSERT INTO memories (project_id, kind, content, source_event_id, created_by_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertMemoryParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	Kind           string      `json:"kind"`
	Content        string      `json:"content"`
	SourceEventID  pgtype.UUID `json:"source_event_id"`
	CreatedByAgent *string     `json:"created_by_agent"`
}

// Persist one distilled memory. project_id routes the row to its tenant partition, which must
// already exist (memories is LIST-partitioned with no default partition, so an un-provisioned
// project fails loud rather than silently mis-routing). Provenance — source_event_id and
// created_by_agent — is resolved by the caller from the event the memory was distilled from;
// source_event_id is nullable only for manual (non-extracted) writes. Everything else takes its
// schema default: trust_tier 'normal', review_status 'auto_approved', version 1, valid_from now(),
// empty entities/scope_keys — the single-schema basic behaviour the OSS build always writes.
func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertMemory,
		arg.ProjectID,
		arg.Kind,
		arg.Content,
		arg.SourceEventID,
		arg.CreatedByAgent,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
