// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMemoryVersion = `-- name: InsertMemoryVersion :one
INSERT INTO memory_versions (project_id, memory_id, version, content, changed_by, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING memory_id, version, content, changed_by, reason, created_at, project_id
`

type InsertMemoryVersionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	MemoryID  pgtype.UUID `json:"memory_id"`
	Version   int32       `json:"version"`
	Content   string      `json:"content"`
	ChangedBy *string     `json:"changed_by"`
	Reason    *string     `json:"reason"`
}

func (q *Queries) InsertMemoryVersion(ctx context.Context, arg InsertMemoryVersionParams) (MemoryVersion, error) {
	row := q.db.QueryRow(ctx, insertMemoryVersion,
		arg.ProjectID,
		arg.MemoryID,
		arg.Version,
		arg.Content,
		arg.ChangedBy,
		arg.Reason,
	)
	var i MemoryVersion
	err := row.Scan(
		&i.MemoryID,
		&i.Version,
		&i.Content,
		&i.ChangedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.ProjectID,
	)
	return i, err
}

const listMemoryVersions = `-- name: ListMemoryVersions :many
SELECT memory_id, version, content, changed_by, reason, created_at, project_id
FROM memory_versions
WHERE project_id = $1 AND memory_id = $2
ORDER BY version
`

type ListMemoryVersionsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	MemoryID  pgtype.UUID `json:"memory_id"`
}

func (q *Queries) ListMemoryVersions(ctx context.Context, arg ListMemoryVersionsParams) ([]MemoryVersion, error) {
	rows, err := q.db.Query(ctx, listMemoryVersions, arg.ProjectID, arg.MemoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryVersion
	for rows.Next() {
		var i MemoryVersion
		if err := rows.Scan(
			&i.MemoryID,
			&i.Version,
			&i.Content,
			&i.ChangedBy,
			&i.Reason,
			&i.CreatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
