// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	KeyHash   string             `json:"key_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Claim struct {
	ID           pgtype.UUID        `json:"id"`
	MemoryID     pgtype.UUID        `json:"memory_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	EntityID     pgtype.UUID        `json:"entity_id"`
	Predicate    string             `json:"predicate"`
	Value        []byte             `json:"value"`
	EventTime    pgtype.Timestamptz `json:"event_time"`
	SupersededBy pgtype.UUID        `json:"superseded_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Entity struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	Aliases      []string           `json:"aliases"`
	DegreeCached int32              `json:"degree_cached"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EntityLink struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	SrcEntityID  pgtype.UUID        `json:"src_entity_id"`
	DstEntityID  pgtype.UUID        `json:"dst_entity_id"`
	Predicate    string             `json:"predicate"`
	Weight       float32            `json:"weight"`
	TrustTier    int16              `json:"trust_tier"`
	ValidFrom    pgtype.Timestamptz `json:"valid_from"`
	ValidTo      pgtype.Timestamptz `json:"valid_to"`
	SupersededBy pgtype.UUID        `json:"superseded_by"`
	Provenance   []pgtype.UUID      `json:"provenance"`
	FirstSeenSeq int64              `json:"first_seen_seq"`
	LastSeenSeq  int64              `json:"last_seen_seq"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	AgentID   string             `json:"agent_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Memory struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Kind           string             `json:"kind"`
	Content        string             `json:"content"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Entities       []byte             `json:"entities"`
	ValidFrom      pgtype.Timestamptz `json:"valid_from"`
	ValidTo        pgtype.Timestamptz `json:"valid_to"`
	SupersededBy   pgtype.UUID        `json:"superseded_by"`
	TrustTier      string             `json:"trust_tier"`
	ReviewStatus   string             `json:"review_status"`
	CreatedByAgent *string            `json:"created_by_agent"`
	SourceEventID  pgtype.UUID        `json:"source_event_id"`
	ScopeKeys      []string           `json:"scope_keys"`
}

type MemoryScope struct {
	MemoryID  pgtype.UUID        `json:"memory_id"`
	ScopeType string             `json:"scope_type"`
	ScopeID   string             `json:"scope_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MemoryVersion struct {
	MemoryID  pgtype.UUID        `json:"memory_id"`
	Version   int32              `json:"version"`
	Content   string             `json:"content"`
	ChangedBy *string            `json:"changed_by"`
	Reason    *string            `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}
