// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	KeyHash   string             `json:"key_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Event struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	AgentID   string             `json:"agent_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Memory struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Kind           string             `json:"kind"`
	Content        string             `json:"content"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Entities       []byte             `json:"entities"`
	ValidFrom      pgtype.Timestamptz `json:"valid_from"`
	ValidTo        pgtype.Timestamptz `json:"valid_to"`
	SupersededBy   pgtype.UUID        `json:"superseded_by"`
	TrustTier      string             `json:"trust_tier"`
	ReviewStatus   string             `json:"review_status"`
	CreatedByAgent *string            `json:"created_by_agent"`
	SourceEventID  pgtype.UUID        `json:"source_event_id"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}
