// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProjectsWithActiveModel = `-- name: ListProjectsWithActiveModel :many
SELECT id FROM projects WHERE active_model_id IS NOT NULL
`

// Every project that has pinned an embedding model. The worker's startup sweep uses it to find projects
// whose vector index is missing (pinned but the build was never enqueued or was lost to a crash) and enqueue
// it, so no project is left permanently on the slower exact-scan path.
// lore:tenant-exempt: a cross-tenant reconciliation scan run by the worker under the RLS-bypass role
func (q *Queries) ListProjectsWithActiveModel(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProjectsWithActiveModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinActiveModelIfUnset = `-- name: PinActiveModelIfUnset :execrows
UPDATE projects
SET active_model_id = $1
WHERE id = $2 AND active_model_id IS NULL
`

type PinActiveModelIfUnsetParams struct {
	ModelID   *string     `json:"model_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// First-wins pin: set the project's active embedding model, but only if it has none yet. The rows affected is
// 1 for the pass that pins it and 0 if it was already pinned — by a prior pass or, under a concurrent race, by
// the one winner. A losing racer blocks on the winner's row lock, and once the winner commits its re-checked
// `active_model_id IS NULL` predicate is false, so it updates no row; exactly one racing first pass gets 1.
// (A snapshot-read sibling CTE could not tell the loser apart from the winner under READ COMMITTED — the
// conditional UPDATE's own row count can.) A 0 result means the caller must read the effective model in a
// fresh statement (which sees the winner's commit) to reject a mismatch before writing vectors in a second
// model's space; a 1 result means this pass chose the model, so it can trigger a one-time index build for the
// newly pinned partition.
// lore:tenant-exempt: projects is the tenant root; it is scoped by its own id (the RLS subject), not project_id
func (q *Queries) PinActiveModelIfUnset(ctx context.Context, arg PinActiveModelIfUnsetParams) (int64, error) {
	result, err := q.db.Exec(ctx, pinActiveModelIfUnset, arg.ModelID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
