// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pack.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPackLog = `-- name: InsertPackLog :exec
INSERT INTO pack_logs (
    project_id, run_id, query,
    covered_seq, freshness_lag_ms, latency_ms,
    scopes, token_budget, est_source_tokens, packed_tokens, tokens_saved,
    memory_ids, pack_hash
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13
)
`

type InsertPackLogParams struct {
	ProjectID       pgtype.UUID   `json:"project_id"`
	RunID           pgtype.UUID   `json:"run_id"`
	Query           string        `json:"query"`
	CoveredSeq      *int64        `json:"covered_seq"`
	FreshnessLagMs  *int32        `json:"freshness_lag_ms"`
	LatencyMs       *int32        `json:"latency_ms"`
	Scopes          []string      `json:"scopes"`
	TokenBudget     *int32        `json:"token_budget"`
	EstSourceTokens *int32        `json:"est_source_tokens"`
	PackedTokens    *int32        `json:"packed_tokens"`
	TokensSaved     *int32        `json:"tokens_saved"`
	MemoryIds       []pgtype.UUID `json:"memory_ids"`
	PackHash        []byte        `json:"pack_hash"`
}

// One row per context-pack request, for run trace and observability. It is written in the SAME transaction as
// the pack's reads, so the pack and its trace commit together — a failed insert fails the pack, and there is
// never an unaccounted pack. tokens_saved is passed NULL in this increment (a downstream metering pass defines
// it from est_source_tokens/packed_tokens); pack_hash is NULL until a later increment computes a byte-stable
// digest. project_id is explicit for tenant isolation; run_id is the run the pack was taken in.
func (q *Queries) InsertPackLog(ctx context.Context, arg InsertPackLogParams) error {
	_, err := q.db.Exec(ctx, insertPackLog,
		arg.ProjectID,
		arg.RunID,
		arg.Query,
		arg.CoveredSeq,
		arg.FreshnessLagMs,
		arg.LatencyMs,
		arg.Scopes,
		arg.TokenBudget,
		arg.EstSourceTokens,
		arg.PackedTokens,
		arg.TokensSaved,
		arg.MemoryIds,
		arg.PackHash,
	)
	return err
}

const packFreshness = `-- name: PackFreshness :one
SELECT coalesce(extract(epoch FROM now() - min(events.created_at)) * 1000, 0)::bigint AS freshness_lag_ms
FROM events
WHERE events.project_id = $1 AND events.run_id = $2
  AND events.seq > $3
`

type PackFreshnessParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	RunID      pgtype.UUID `json:"run_id"`
	CoveredSeq int64       `json:"covered_seq"`
}

// How far behind the run's distilled view is: the age, in milliseconds by the database clock, of the OLDEST
// event past the extraction checkpoint — the longest a not-yet-distilled write has waited. Zero when the run
// is fully caught up (no uncovered events). This is the single definition of the pack's freshness lag.
// covered_seq is passed in (read once) so it agrees with the raw tail. Project-scoped.
func (q *Queries) PackFreshness(ctx context.Context, arg PackFreshnessParams) (int64, error) {
	row := q.db.QueryRow(ctx, packFreshness, arg.ProjectID, arg.RunID, arg.CoveredSeq)
	var freshness_lag_ms int64
	err := row.Scan(&freshness_lag_ms)
	return freshness_lag_ms, err
}

const packRawTailBeyond = `-- name: PackRawTailBeyond :many
SELECT id, agent_id, payload, created_at, seq
FROM events
WHERE project_id = $1 AND run_id = $2
  AND seq > GREATEST($3::bigint, $4::bigint)
ORDER BY seq DESC
LIMIT $5::int
`

type PackRawTailBeyondParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	RunID      pgtype.UUID `json:"run_id"`
	CoveredSeq int64       `json:"covered_seq"`
	MinSeq     int64       `json:"min_seq"`
	MaxEvents  int32       `json:"max_events"`
}

type PackRawTailBeyondRow struct {
	ID        pgtype.UUID        `json:"id"`
	AgentID   string             `json:"agent_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Seq       int64              `json:"seq"`
}

// The recent-context tail: a run's not-yet-distilled events PAST the guaranteed read-your-writes window (seq
// greater than BOTH the checkpoint and min_seq), newest first, capped. This is best-effort extra context — a
// stalled extraction can leave many uncovered events, and this bounds how many the pack carries beyond what
// the caller explicitly asked to see, so a pack can never grow unboundedly. The caller fetches one more than
// the cap to detect truncation, then reverses into seq order. When min_seq is at or below the checkpoint the
// lower bound collapses to the checkpoint, so this returns the newest uncovered events. Project-scoped.
func (q *Queries) PackRawTailBeyond(ctx context.Context, arg PackRawTailBeyondParams) ([]PackRawTailBeyondRow, error) {
	rows, err := q.db.Query(ctx, packRawTailBeyond,
		arg.ProjectID,
		arg.RunID,
		arg.CoveredSeq,
		arg.MinSeq,
		arg.MaxEvents,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackRawTailBeyondRow
	for rows.Next() {
		var i PackRawTailBeyondRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Payload,
			&i.CreatedAt,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packRawTailGuaranteed = `-- name: PackRawTailGuaranteed :many
SELECT id, agent_id, payload, created_at, seq
FROM events
WHERE project_id = $1 AND run_id = $2
  AND seq > $3 AND seq <= $4
ORDER BY seq
`

type PackRawTailGuaranteedParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	RunID      pgtype.UUID `json:"run_id"`
	CoveredSeq int64       `json:"covered_seq"`
	MinSeq     int64       `json:"min_seq"`
}

type PackRawTailGuaranteedRow struct {
	ID        pgtype.UUID        `json:"id"`
	AgentID   string             `json:"agent_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Seq       int64              `json:"seq"`
}

// The read-your-writes window: a run's not-yet-distilled events from just past the extraction checkpoint up
// to and including the seq the caller asked to see (min_seq). These are ALWAYS returned in full — the pack's
// correctness guarantee that a reader sees a write it knows happened — so this query carries no cap (the
// window is bounded by min_seq itself). Empty when min_seq is at or below the checkpoint. covered_seq is
// passed in, read once by the caller, so every part of one pack sees the same checkpoint. Project-scoped, and
// the UNIQUE (run_id, seq) index backs the range scan.
func (q *Queries) PackRawTailGuaranteed(ctx context.Context, arg PackRawTailGuaranteedParams) ([]PackRawTailGuaranteedRow, error) {
	rows, err := q.db.Query(ctx, packRawTailGuaranteed,
		arg.ProjectID,
		arg.RunID,
		arg.CoveredSeq,
		arg.MinSeq,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackRawTailGuaranteedRow
	for rows.Next() {
		var i PackRawTailGuaranteedRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Payload,
			&i.CreatedAt,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
