// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrieval.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const countRetrievalCandidates = `-- name: CountRetrievalCandidates :one
SELECT count(*) FROM (
    SELECT 1
    FROM memories m
    JOIN embeddings e ON e.project_id = m.project_id AND e.memory_id = m.id
    WHERE m.project_id = $1 AND e.project_id = $1
      AND e.model_id = $2
      AND m.superseded_by IS NULL AND m.valid_to IS NULL
      AND (cardinality($3::text[]) = 0 OR m.scope_keys && $3::text[])
      AND ($4::bool OR m.trust_tier <> 'quarantine')
    LIMIT $5::int
) t
`

type CountRetrievalCandidatesParams struct {
	ProjectID         pgtype.UUID `json:"project_id"`
	ModelID           string      `json:"model_id"`
	Scopes            []string    `json:"scopes"`
	IncludeQuarantine bool        `json:"include_quarantine"`
	ScanLimit         int32       `json:"scan_limit"`
}

// Count the live memories matching the retrieval filters, BOUNDED to the crossover threshold + 1: the
// retriever only needs to know whether the filtered set is small (exact scan) or large (index-backed), so
// it counts at most scan_limit rows via the inner LIMIT, never a full COUNT(*) over a large partition.
// Empty scopes means project-wide; include_quarantine=false (the default) excludes quarantine-tier
// memories. The filter shape is the compiled-ACL slot: L2 changes only where scopes comes from, not the
// && overlap. Tenant partition = project_id (on both tables); scope_keys && uses the GIN index.
func (q *Queries) CountRetrievalCandidates(ctx context.Context, arg CountRetrievalCandidatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRetrievalCandidates,
		arg.ProjectID,
		arg.ModelID,
		arg.Scopes,
		arg.IncludeQuarantine,
		arg.ScanLimit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveModelID = `-- name: GetActiveModelID :one
SELECT active_model_id FROM projects WHERE id = $1
`

// The project's active embedding model — the single model space a read queries. NULL until a model is
// chosen; the retriever treats that as a loud, typed error, never a silent empty result. Scoped by the
// project's own id, which is the tenant root's RLS subject (projects is scoped by id, not project_id).
// lore:tenant-exempt: projects is the tenant root; it is scoped by its own id (the RLS subject), not project_id
func (q *Queries) GetActiveModelID(ctx context.Context, id pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getActiveModelID, id)
	var active_model_id *string
	err := row.Scan(&active_model_id)
	return active_model_id, err
}

const retrieveExact = `-- name: RetrieveExact :many
SELECT m.id, m.content, m.kind, (e.vec <=> $1::vector)::float8 AS distance
FROM memories m
JOIN embeddings e ON e.project_id = m.project_id AND e.memory_id = m.id
WHERE m.project_id = $2 AND e.project_id = $2
  AND e.model_id = $3
  AND m.superseded_by IS NULL AND m.valid_to IS NULL
  AND (cardinality($4::text[]) = 0 OR m.scope_keys && $4::text[])
  AND ($5::bool OR m.trust_tier <> 'quarantine')
ORDER BY distance ASC
LIMIT $6::int
`

type RetrieveExactParams struct {
	QueryVec          pgvector.Vector `json:"query_vec"`
	ProjectID         pgtype.UUID     `json:"project_id"`
	ModelID           string          `json:"model_id"`
	Scopes            []string        `json:"scopes"`
	IncludeQuarantine bool            `json:"include_quarantine"`
	MaxResults        int32           `json:"max_results"`
}

type RetrieveExactRow struct {
	ID       pgtype.UUID `json:"id"`
	Content  string      `json:"content"`
	Kind     string      `json:"kind"`
	Distance float64     `json:"distance"`
}

// The exact-scan retrieval path: the filtered live memories nearest the query vector by cosine distance,
// used when the filtered candidate set is small (or no valid index exists). It deliberately does NOT cast
// vec to a fixed dimension, so it never matches the HNSW expression index and always scans exactly —
// correct for a small set, and correct in the window before the index is built. Same filter shape as the
// count. (The index-backed path is a dynamically-built query because the vector(D) typmod cannot be a bind
// parameter — see core/retrieval.)
func (q *Queries) RetrieveExact(ctx context.Context, arg RetrieveExactParams) ([]RetrieveExactRow, error) {
	rows, err := q.db.Query(ctx, retrieveExact,
		arg.QueryVec,
		arg.ProjectID,
		arg.ModelID,
		arg.Scopes,
		arg.IncludeQuarantine,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrieveExactRow
	for rows.Next() {
		var i RetrieveExactRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Kind,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveLexical = `-- name: RetrieveLexical :many
SELECT m.id, m.content, m.kind,
       ts_rank_cd(to_tsvector('english', m.content), websearch_to_tsquery('english', $1::text))::float8 AS rank
FROM memories m
WHERE m.project_id = $2
  AND m.superseded_by IS NULL AND m.valid_to IS NULL
  AND (cardinality($3::text[]) = 0 OR m.scope_keys && $3::text[])
  AND ($4::bool OR m.trust_tier <> 'quarantine')
  AND to_tsvector('english', m.content) @@ websearch_to_tsquery('english', $1::text)
ORDER BY rank DESC, m.id ASC
LIMIT $5::int
`

type RetrieveLexicalParams struct {
	QueryText         string      `json:"query_text"`
	ProjectID         pgtype.UUID `json:"project_id"`
	Scopes            []string    `json:"scopes"`
	IncludeQuarantine bool        `json:"include_quarantine"`
	MaxResults        int32       `json:"max_results"`
}

type RetrieveLexicalRow struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
	Kind    string      `json:"kind"`
	Rank    float64     `json:"rank"`
}

// The lexical (full-text) retrieval leg: the live memories whose content matches the query terms, ranked by
// lexical relevance. It complements the dense vector leg — an exact keyword or identifier match a nearest-
// neighbour vector search misses, and vice versa — and the two are fused by rank downstream, which is why
// the raw rank is not returned to the caller (only the order matters). The match uses an English text-search
// configuration over content, backed by an expression GIN index on the identical to_tsvector('english',
// content) expression, so the predicate is index-usable; a drift between this expression and the index's
// would silently fall to a sequential scan. An empty or all-stopword query produces an empty tsquery that
// matches nothing, so the leg contributes no candidates rather than every row. Same filter shape as the
// dense leg: the tenant is the project partition, scope_keys && is the compiled-ACL overlap (empty =
// project-wide), quarantine-tier excluded unless asked. The id tie-break makes equal-rank order stable.
func (q *Queries) RetrieveLexical(ctx context.Context, arg RetrieveLexicalParams) ([]RetrieveLexicalRow, error) {
	rows, err := q.db.Query(ctx, retrieveLexical,
		arg.QueryText,
		arg.ProjectID,
		arg.Scopes,
		arg.IncludeQuarantine,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrieveLexicalRow
	for rows.Next() {
		var i RetrieveLexicalRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Kind,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
