// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (project_id)
VALUES ($1)
RETURNING id, started_at
`

type CreateRunRow struct {
	ID        pgtype.UUID        `json:"id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

// Create a run in the caller's project and return its id and start time. project_id is supplied by the
// authenticated key (never a client body), and it is carried on the inserted row, so a run can only be
// born in the key's own project — tenant-scoped by construction. The handler runs this inside a
// project-scoped transaction (WithProject); the request carries no other run fields today.
func (q *Queries) CreateRun(ctx context.Context, projectID pgtype.UUID) (CreateRunRow, error) {
	row := q.db.QueryRow(ctx, createRun, projectID)
	var i CreateRunRow
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}
