// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (project_id, key_hash)
VALUES ($1, $2)
RETURNING id, project_id, key_hash, created_at, revoked_at
`

type InsertAPIKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	KeyHash   string      `json:"key_hash"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey, arg.ProjectID, arg.KeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertOrganization = `-- name: InsertOrganization :one

INSERT INTO organizations (name)
VALUES ($1)
RETURNING id, name, created_at
`

// Bootstrap inserts for the org -> project -> run chain an event needs, plus the
// API key row. Used by wiring and tests until a control plane owns these.
func (q *Queries) InsertOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, insertOrganization, name)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (org_id, name)
VALUES ($1, $2)
RETURNING id, org_id, name, created_at, active_model_id, retain_events_days, retain_memories_days
`

type InsertProjectParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
}

// lore:tenant-exempt: creates the tenant (projects) row itself — there is no project to scope by
func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.ActiveModelID,
		&i.RetainEventsDays,
		&i.RetainMemoriesDays,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (project_id)
VALUES ($1)
RETURNING id, project_id, status, started_at, last_seq
`

type InsertRunRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	LastSeq   int64              `json:"last_seq"`
}

func (q *Queries) InsertRun(ctx context.Context, projectID pgtype.UUID) (InsertRunRow, error) {
	row := q.db.QueryRow(ctx, insertRun, projectID)
	var i InsertRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.StartedAt,
		&i.LastSeq,
	)
	return i, err
}
