// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: working_facts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRunWorkingFacts = `-- name: ListRunWorkingFacts :many
SELECT entity, predicate, value, seq, agent_id
FROM working_facts
WHERE project_id = $1 AND run_id = $2
ORDER BY seq DESC, entity, predicate
`

type ListRunWorkingFactsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

type ListRunWorkingFactsRow struct {
	Entity    string `json:"entity"`
	Predicate string `json:"predicate"`
	Value     []byte `json:"value"`
	Seq       int64  `json:"seq"`
	AgentID   string `json:"agent_id"`
}

// One run's working memory, freshest first — the pack's working section. Scoped to the run, not the
// project: two runs may hold different values for the same subject, and each must see its own.
// Served by the primary key as a prefix range scan.
//
// The ORDER BY gives the query a stable plan and a declared contract, but the pack re-sorts in Go:
// Postgres orders text by the database's collation while the pack's determinism guarantee is over
// bytes, so leaving the final order to SQL would make a pack's bytes depend on the server's locale.
func (q *Queries) ListRunWorkingFacts(ctx context.Context, arg ListRunWorkingFactsParams) ([]ListRunWorkingFactsRow, error) {
	rows, err := q.db.Query(ctx, listRunWorkingFacts, arg.ProjectID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunWorkingFactsRow
	for rows.Next() {
		var i ListRunWorkingFactsRow
		if err := rows.Scan(
			&i.Entity,
			&i.Predicate,
			&i.Value,
			&i.Seq,
			&i.AgentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkingFact = `-- name: UpsertWorkingFact :execrows
INSERT INTO working_facts (project_id, run_id, entity, predicate, value, seq, agent_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
ON CONFLICT (project_id, run_id, entity, predicate) DO UPDATE
SET value      = EXCLUDED.value,
    seq        = EXCLUDED.seq,
    agent_id   = EXCLUDED.agent_id,
    updated_at = now()
WHERE working_facts.seq < EXCLUDED.seq
`

type UpsertWorkingFactParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	RunID     pgtype.UUID `json:"run_id"`
	Entity    string      `json:"entity"`
	Predicate string      `json:"predicate"`
	Value     []byte      `json:"value"`
	Seq       int64       `json:"seq"`
	AgentID   string      `json:"agent_id"`
}

// Record a run's current value for one subject, from the transaction that appends the state event
// carrying it. Sharing that transaction is the whole durability story: the event and the fact behind
// it commit together or not at all, so a caller holding an event's seq is guaranteed a pack can
// already see the fact.
//
// The seq guard keeps the row's meaning local and self-evident — `seq` is always the highest event
// seq that has written this subject — rather than something a reader has to infer from elsewhere.
// Concurrent writers of one run are already serialised upstream (InsertEvent bumps the run counter
// with a row lock held to commit), so the guard is not what orders today's ingest; it is what keeps
// the invariant true for anything that is NOT serialised that way — a replay, a backfill, or a
// second writer added later — and it makes a redelivered write a no-op instead of a rewrite.
//
// :execrows, deliberately not :one. When the guard suppresses a stale write the statement affects no
// rows; with RETURNING that would surface as ErrNoRows and a caller would have to treat "a newer
// value already won" as a failure — rolling back a perfectly good event. Zero rows here is a normal
// outcome, not an error.
func (q *Queries) UpsertWorkingFact(ctx context.Context, arg UpsertWorkingFactParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertWorkingFact,
		arg.ProjectID,
		arg.RunID,
		arg.Entity,
		arg.Predicate,
		arg.Value,
		arg.Seq,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
